// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMUga8GB1goKZaDQBzlV9Gu--pHZe_MVA',
    appId: '1:878895227518:web:4faac60e763dcef1176e2f',
    messagingSenderId: '878895227518',
    projectId: 'colportorgoals-and-finances',
    authDomain: 'colportorgoals-and-finances.firebaseapp.com',
    storageBucket: 'colportorgoals-and-finances.firebasestorage.app',
    measurementId: 'G-D6XH87M2GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKesyBM3lYv5OrxSfAZdRDnRciyHE2ifA',
    appId: '1:878895227518:android:4205ad68a8c27aaf176e2f',
    messagingSenderId: '878895227518',
    projectId: 'colportorgoals-and-finances',
    storageBucket: 'colportorgoals-and-finances.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_kZgrPqoQDIjZ4i8fU3e_y2rhf1x0zQ',
    appId: '1:878895227518:ios:60b848fa8025224f176e2f',
    messagingSenderId: '878895227518',
    projectId: 'colportorgoals-and-finances',
    storageBucket: 'colportorgoals-and-finances.firebasestorage.app',
    iosBundleId: 'com.example.meuPrimeiroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_kZgrPqoQDIjZ4i8fU3e_y2rhf1x0zQ',
    appId: '1:878895227518:ios:60b848fa8025224f176e2f',
    messagingSenderId: '878895227518',
    projectId: 'colportorgoals-and-finances',
    storageBucket: 'colportorgoals-and-finances.firebasestorage.app',
    iosBundleId: 'com.example.meuPrimeiroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMUga8GB1goKZaDQBzlV9Gu--pHZe_MVA',
    appId: '1:878895227518:web:d055fabd7fd90708176e2f',
    messagingSenderId: '878895227518',
    projectId: 'colportorgoals-and-finances',
    authDomain: 'colportorgoals-and-finances.firebaseapp.com',
    storageBucket: 'colportorgoals-and-finances.firebasestorage.app',
    measurementId: 'G-LXLCS2HE50',
  );
}
